### ISSUE TITLE
Unable to uptade the debug log option set

### ISSUE THREAD

**Issue by ChrysMa** [sinseman44/koolnova-BMS-Integration#11]
Hello,
Thanks a lot for your integration. 
However when I first installed it, I checked the "debug log" option . Now I am unable to stop it from logging. Is there any convenient way but to remove/reinstall it ?
Thanks ;-)

**Comment by sinseman44** [comment]
Hi ChrysMa,

If you activate debug mode in the configuration view (activate pymodbus debug level), you must re-install it to deactivate this debug mode.
In the next release, I will try to put an command to deactivate the debug mode without re-install the integration.
Sorry for the huge log file.

**Comment by ChrysMa** [comment]
Thanks ;-) BTW the log is not a matter of concern..

**Comment by sinseman44** [comment]
Correction done on release v0.2.0
