### ISSUE TITLE
Solution in case address 49 does not work

### ISSUE THREAD

**Issue by mauroartizzu** [sinseman44/koolnova-BMS-Integration#4]
Just in case someone faces my issue, I had to set INT49 on the koolnova master remote but address 1 on homeassistant configuration, koolnova customer support helped me in that way, now the communication works.

Feel free to close the issue as it's solved

![image](https://github.com/sinseman44/koolnova-BMS-Integration/assets/567423/96be61ca-1e59-4159-b118-fb815c9807e9)

**Comment by sinseman44** [comment]
Hi Mauro,

Glad to see your setup works with this. I modified the README to warn future users. I have always configured the default koolnova address on my installation without encountering any problems.
The official documentation says : 
"_System address :
Each control unit has a specific address (default 49).
Possible addresses are 1 to 247, so you can put up to 247 control units in a parallel-connected project_"

There is a modbus register (40078 in Read/Write) that set/get koolnova modbus address. this integration doesn't interact with this register.
Maybe this address was changed in your controller ?

**Comment by mauroartizzu** [comment]
Maybe, it was installed by a third party I didn't install it by myself, so it is possible they reconfigure the controllers. Anyway thanks for the update in the readme. I hope that could help other people too :)

**Comment by Lk1975** [comment]
It works! It has arrived today the same usb dongle as yours, connected and it works! I've now setup in a second homassistance the connection with Koolnova. So far so good. Thanks
