### ISSUE TITLE
Temperature shown in F instead of C

### ISSUE THREAD

**Issue by FedericoFedeFede** [sinseman44/koolnova-BMS-Integration#5]
I can't find in the setting how to switch F to C
![image](https://github.com/user-attachments/assets/180b5ef4-694e-42e0-b8eb-c7d5b9af51f2)

**Comment by sinseman44** [comment]
Hi,
Did you verify in the general settings (Parameters -> System -> General) of your Home Assistant that the parameter metrics 
Celcius, Kilogram is checked and not Fahrenheit, Pound ?

**Comment by FedericoFedeFede** [comment]
With the new update, everything is correct now
