### ISSUE TITLE
HA Crash when add integration Koolonova

### ISSUE THREAD

**Issue by sadibisc** [sinseman44/koolnova-BMS-Integration#7]
Hello,
I have : 
- HA Core 2024.9.3 (same problem also found with 2024.9.2 ) on Linux Lite (Virtual Box)
- DSD TECH SH-U11 Converter  USB to RS485
- INT 49 enabled on the master thermostat
- Koolnova 100-CPND00 control unit
The USB device is shown in Linux command line and HA (with "dmesg | grep USB" I see "FTDI USB Serial Device converter now attached to ttyUSB0").
I installed Koolnova by repository successfully but when I try to add Integration HA, with the indicated parameters  (/dev/ttyUSB - 49 or 1 - 9600 - EVEN), it crashed and I have to restart the Virtual Box machine.
I tried previosly with another JZK Adapter USB to RS485 adapter with the same result
Can you help me ?
Thanks
Bye 
Sabino

**Comment by sinseman44** [comment]
Hi Sabino,
Can you attach some log of your Home Assistant to see what happens ?

**Comment by sadibisc** [comment]
Hi sinseman44,
I found that the problem, it was not with Home Assistant but with the PC hosting HA. I exported HA to a Raspberry and the integration works well
I can close the issue
Thanks a lot

**Comment by sadibisc** [comment]
Hi sinseman44,
I found that the problem, it was not with Home Assistant but with the PC hosting HA. I exported HA to a Raspberry and the integration works well
I can close the issue
Thanks a lot
